function handleRedirectFeedCheckbox(checkbox) {
  if (checkbox.checked) {
    document.getElementById('ultimatecrawloptimizer_remove_global_feed').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_global_feed').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_global_comment_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_global_comment_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_post_comments_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_post_comments_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_post_authors_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_post_authors_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_post_type_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_post_type_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_category_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_category_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_tag_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_tag_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_custom_taxonomy_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_custom_taxonomy_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_search_results_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_search_results_feeds').disabled = true;
    document.getElementById('ultimatecrawloptimizer_remove_atom_rdf_feeds').checked = true;
    document.getElementById('ultimatecrawloptimizer_remove_atom_rdf_feeds').disabled = true;
  } else {
    document.getElementById('ultimatecrawloptimizer_remove_global_feed').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_global_feed').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_global_comment_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_global_comment_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_post_comments_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_post_comments_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_post_authors_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_post_authors_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_post_type_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_post_type_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_category_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_category_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_tag_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_tag_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_custom_taxonomy_feeds').checked = false;
    document.getElementById('ultimatecrawloptimizer_remove_custom_taxonomy_feeds').disabled = false;
    document.getElementById('ultimatecrawloptimizer_remove_search_results_feeds').checked = false;
	document.getElementById('ultimatecrawloptimizer_remove_search_results_feeds').disabled = false;
	document.getElementById('ultimatecrawloptimizer_remove_atom_rdf_feeds').checked = false;
	document.getElementById('ultimatecrawloptimizer_remove_atom_rdf_feeds').disabled = false;
}
}